# Site settings
title: SCAR Krill Expert Group (SKEG)
email: zephyr.sylvester@colorado.edu
description: >-
  The main SKEG website is temporarily down for maintenance.
  This page will serve as the hub for all updates until further notice.
baseurl: ""
url: ""
github_username: SCAR-Krill-Expert-Group

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from

# Site logo (appears in masthead)
logo: "/assets/logos/logo-SKEG-3.2-black-text.png"

# Defaults for pages and posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
