theme: tactile
author: SKEG Communications & Outreach Task Force
description: SKEG provides a forum to guide research directions, promote collaboration, improve understanding of krill biology and ecology, and thus assist in providing critical scientific information relevant to krill fishery management. 
